export const calculatorActions = Object.freeze({
  SET_MORTGAGE_AMOUNT: 'SET_MORTGAGE_AMOUNT',
  SET_MORTGAGE_TERM: 'SET_MORTGAGE_TERM',
  SET_MORTGAGE_INTEREST_RATE: 'SET_MORTGAGE_INTEREST_RATE',
  SET_MORTGAGE_TYPE: 'SET_MORTGAGE_TYPE',
  SET_ERROR: 'SET_ERROR',
  GET_RESULTS: 'GET_RESULTS',
  RESET_CALCULATOR: 'RESET_CALCULATOR'
})